Improve performance by disabling automatic raw data updates
klavarog/keyboard-layout-editor pull request #11
Opened 2020-03-23 08:33 UTC by bouncepaw

I added a button to force update and an explanatory text.

2020-03-23 13:49 UTC, optozorax requested changes
![изображение](https://user-images.githubusercontent.com/18114381/77323388-c006d400-6d47-11ea-9770-bf083efdf213.png)

2020-03-23 13:49 UTC, optozorax commented on backgrounds.json
> +      "category": "Carbon fibre", "style" : "background: url('/bg/carbonfibre/carbon-slice.jpg'); color: #fff;",
Надо убрать эти мусорные изменения

2020-03-23 13:49 UTC, optozorax commented on build/config.gypi
> +# Do not edit. File was generated by node-gyp's "configure" step
Что это? Это разве не выхлоп билдера? По идее он не нужен в мастере. Если да, то добавь его в .gitignore

2020-03-23 13:49 UTC, optozorax commented on deploy/nginx.conf
> +		root /home/bouncepaw/src/keyboard-layout-editor/;
Это тоже нельзя коммитить

2020-03-23 13:49 UTC, optozorax commented on CHANGELOG.md
> +___Version 0.15+klavarog patches:___ Mar 23, 2020
пусть будет версия 0.16, ато так слишком длинно

2020-03-23 13:49 UTC, optozorax commented on kb.js
> +		$scope.version = "0.15+klavarog patches";
Аналогично с версией

2020-03-23 13:49 UTC, optozorax commented on kb.html
> +      <button class="btn btn-primary" onclick="kostyl()">Update Raw data</button>
А сразу нельзя updateSerialized вызывать?

2020-03-23 13:49 UTC, optozorax commented on kb.js
> +                        console.log("updateSerialized was called");
дебаг надо убрать из релизной версии -_-
ты не чекаешь что коммитишь?

2020-03-23 13:49 UTC, optozorax commented on kb.js
> +				//if(type !== 'rawdata') {
Когда что-то выпиливаешь, строки надо удалять, а не комментить

2020-03-23 13:49 UTC, optozorax commented on kb.js
> +			//updateSerialized();
Больше эта функция нигде не вызывается? Проверил?

2020-03-23 13:49 UTC, optozorax commented on kb.js
> +                kostyl = updateSerialized;
неправильные отступы, используй табы, как в оригинальном коде

2020-03-23 13:49 UTC, optozorax commented on deploy/nginx.conf
> +}
ну это норм, можно оставить

2020-03-23 14:04 UTC, bouncepaw commented on CHANGELOG.md
> +___Version 0.15+klavarog patches:___ Mar 23, 2020
Имеем ли мы, форкеры, на это право?

2020-03-23 14:05 UTC, bouncepaw commented on build/config.gypi
> +# Do not edit. File was generated by node-gyp's "configure" step
У меня без этой херни не работало

2020-03-23 14:06 UTC, bouncepaw commented on kb.html
> +      <button class="btn btn-primary" onclick="kostyl()">Update Raw data</button>
Нет, там она в закрытом скоупе, я вот так на топ-левел вытащил

2020-03-23 14:06 UTC, bouncepaw commented on kb.js
> +                        console.log("updateSerialized was called");
Я чекал и заметил, что эта штука тут. Ну, ок

2020-03-23 15:53 UTC, optozorax commented on build/config.gypi
> +# Do not edit. File was generated by node-gyp's "configure" step
Без исполняемого файла и объектным файлов программа на Си тоже не работает, но это ведь не повод их коммитить в мастер!

2020-03-23 15:53 UTC, optozorax commented on CHANGELOG.md
> +___Version 0.15+klavarog patches:___ Mar 23, 2020
если сомневаешься, тогда вообще лучше не трогать номера версий

2020-03-23 15:55 UTC, optozorax commented on kb.html
> +      <button class="btn btn-primary" onclick="kostyl()">Update Raw data</button>
Ладно, но функцию назови по-нормальному. Типо publicUpdateSerialized

2020-03-25 12:20 UTC, bouncepaw commented on kb.js
> +			//updateSerialized();
она ещё вызывается в некоторых местах, но там уместно, оставлю

2020-03-25 15:18 UTC, optozorax approved these changes

2020-03-25 15:18 UTC, merged